# Generated by Django 5.2 on 2025-06-24 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arosaje', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consentments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('required', models.BooleanField(default=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConsentmentAcceptances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentment_acceptances', to=settings.AUTH_USER_MODEL)),
                ('consentment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='arosaje.consentments')),
            ],
        ),
    ]
