# Generated by Django 5.2 on 2025-06-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arosaje', '0002_consentments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversations',
            old_name='user2',
            new_name='keeper',
        ),
        migrations.RenameField(
            model_name='conversations',
            old_name='user1',
            new_name='owner',
        )
    ]
