services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes: ["./backend:/app"]
    command: ["python", "/app/manage.py", "runserver", "--nothreading", "0.0.0.0:8000"]
    ports:
      - "${HOST_FRONTEND_PORT-8000}:8000" # Django BO
       
  frontend:
    image: node:22.15.1-alpine3.20
    volumes: ["./frontend:/app"]
    working_dir: "/app"
    command: ['sh', '-c', '[ ! -d node_modules ] && yarn install; npm run dev -- --host']
    ports:
      - '${HOST_FRONTEND_PORT-5173}:5173'