services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes: ["./backend:/app"]
    command: ["python", "/app/manage.py", "runserver", "--nothreading", "0.0.0.0:8000"]
    ports:
      - "8000:8000" # Django BO
       
     